(defproject raylib-examples "0.1-SNAPSHOT"
  :license {:name "zlib"
            :url  "https://opensource.org/license/zlib"}
  :plugins [[org.jank-lang/lein-jank "2026.06-1"]]
  :middleware [leiningen.jank/middleware]
  :dependencies [[net.b12n/jank-raylib-sys "6.0-SNAPSHOT"]]
  ;; Default entrypoint; select another example with a profile, e.g.
  ;;   lein with-profile +input-keys run --disable-sandbox
  :main raylib-examples.bouncing-ball
  :jank {:target-dir         "target"
         :optimization-level 2}
  :profiles {:bouncing-ball   {:main raylib-examples.bouncing-ball}
             :input-keys      {:main raylib-examples.input-keys}
             :colors-palette  {:main raylib-examples.colors-palette}
             :starfield       {:main raylib-examples.starfield}
             :mouse-trail     {:main raylib-examples.mouse-trail}
             :logo-anim       {:main raylib-examples.logo-anim}
             :double-pendulum {:main raylib-examples.double-pendulum}
             :particles       {:main raylib-examples.particles}
             :input-mouse     {:main raylib-examples.input-mouse}
             :collision-area  {:main raylib-examples.collision-area}
             :ball-physics    {:main raylib-examples.ball-physics}
             :easings-rectangles {:main raylib-examples.easings-rectangles}
             :following-eyes  {:main raylib-examples.following-eyes}
             :lines-bezier    {:main raylib-examples.lines-bezier}
             :rectangle-scaling {:main raylib-examples.rectangle-scaling}
             :dashed-line     {:main raylib-examples.dashed-line}
             :basic-shapes    {:main raylib-examples.basic-shapes}
             :logo-raylib     {:main raylib-examples.logo-raylib}
             :easings-ball    {:main raylib-examples.easings-ball}
             :easings-box     {:main raylib-examples.easings-box}
             :math-angle-rotation {:main raylib-examples.math-angle-rotation}
             :ellipse-collision {:main raylib-examples.ellipse-collision}
             :vector-angle    {:main raylib-examples.vector-angle}
             :penrose-tile    {:main raylib-examples.penrose-tile}
             :input-mouse-wheel {:main raylib-examples.input-mouse-wheel}
             :random-values   {:main raylib-examples.random-values}
             :camera-2d       {:main raylib-examples.camera-2d}
             :basic-window    {:main raylib-examples.basic-window}
             :opaque-boxes    {:main raylib-examples.opaque-boxes}
             :scissor-test    {:main raylib-examples.scissor-test}
             :window-should-close {:main raylib-examples.window-should-close}
             :digital-clock   {:main raylib-examples.digital-clock}
             :clock-of-clocks {:main raylib-examples.clock-of-clocks}
             :delta-time      {:main raylib-examples.delta-time}
             :basic-screen-manager {:main raylib-examples.basic-screen-manager}
             :lines-drawing   {:main raylib-examples.lines-drawing}
             :easings-testbed {:main raylib-examples.easings-testbed}
             :camera-2d-platformer {:main raylib-examples.camera-2d-platformer}
             :input-gestures  {:main raylib-examples.input-gestures}
             :window-letterbox {:main raylib-examples.window-letterbox}
             :camera-2d-split-screen {:main raylib-examples.camera-2d-split-screen}
             :smooth-pixelperfect {:main raylib-examples.smooth-pixelperfect}
             :format-text     {:main raylib-examples.format-text}
             :writing-anim    {:main raylib-examples.writing-anim}
             :input-box       {:main raylib-examples.input-box}
             :words-alignment {:main raylib-examples.words-alignment}
             :bullet-hell     {:main raylib-examples.bullet-hell}
             :ring-drawing    {:main raylib-examples.ring-drawing}
             :circle-sector-drawing {:main raylib-examples.circle-sector-drawing}
             :rounded-rectangle {:main raylib-examples.rounded-rectangle}
             :recursive-tree  {:main raylib-examples.recursive-tree}
             :triangle-strip  {:main raylib-examples.triangle-strip}
             :math-sine-cosine {:main raylib-examples.math-sine-cosine}
             :hilbert-curve   {:main raylib-examples.hilbert-curve}
             :pie-chart       {:main raylib-examples.pie-chart}
             :kaleidoscope    {:main raylib-examples.kaleidoscope}
             :splines-drawing {:main raylib-examples.splines-drawing}
             :rlgl-triangle   {:main raylib-examples.rlgl-triangle}
             :rlgl-color-wheel {:main raylib-examples.rlgl-color-wheel}
             :top-down-lights {:main raylib-examples.top-down-lights}
             :rectangle-advanced {:main raylib-examples.rectangle-advanced}
             :image-generation {:main raylib-examples.image-generation}
             :logo-texture    {:main raylib-examples.logo-texture}
             :sprite-animation {:main raylib-examples.sprite-animation}
             :srcrec-dstrec   {:main raylib-examples.srcrec-dstrec}
             :background-scrolling {:main raylib-examples.background-scrolling}
             :image-loading   {:main raylib-examples.image-loading}
             :blend-modes     {:main raylib-examples.blend-modes}
             :particles-blending {:main raylib-examples.particles-blending}
             :mouse-painting  {:main raylib-examples.mouse-painting}
             :sprite-button   {:main raylib-examples.sprite-button}
             :sound-loading   {:main raylib-examples.sound-loading}
             :bunnymark       {:main raylib-examples.bunnymark}
             :music-stream    {:main raylib-examples.music-stream}
             :module-playing  {:main raylib-examples.module-playing}
             :sound-multi     {:main raylib-examples.sound-multi}
             :fog-of-war      {:main raylib-examples.fog-of-war}
             :sound-positioning {:main raylib-examples.sound-positioning}
             :geometric-shapes {:main raylib-examples.geometric-shapes}
             :box-collisions  {:main raylib-examples.box-collisions}
             :billboard-rendering {:main raylib-examples.billboard-rendering}
             :waving-cubes    {:main raylib-examples.waving-cubes}
             :orthographic-projection {:main raylib-examples.orthographic-projection}
             :tesseract-view  {:main raylib-examples.tesseract-view}
             :rlgl-solar-system {:main raylib-examples.rlgl-solar-system}
             :camera-2d-mouse-zoom {:main raylib-examples.camera-2d-mouse-zoom}
             :world-screen    {:main raylib-examples.world-screen}
             :tiled-drawing   {:main raylib-examples.tiled-drawing}
             :font-loading    {:main raylib-examples.font-loading}
             :font-filters    {:main raylib-examples.font-filters}
             :font-spritefont {:main raylib-examples.font-spritefont}
             :sprite-fonts    {:main raylib-examples.sprite-fonts}
             :camera-3d       {:main raylib-examples.camera-3d}
             :picking-3d      {:main raylib-examples.picking-3d}
             :sprite-explosion {:main raylib-examples.sprite-explosion}
             :input-multitouch {:main raylib-examples.input-multitouch}
             :sprite-stacking {:main raylib-examples.sprite-stacking}
             :npatch-drawing  {:main raylib-examples.npatch-drawing}
             :input-virtual-controls {:main raylib-examples.input-virtual-controls}
             :image-processing {:main raylib-examples.image-processing}
             :image-drawing   {:main raylib-examples.image-drawing}
             :image-text      {:main raylib-examples.image-text}
             :image-rotate    {:main raylib-examples.image-rotate}
             :image-channel   {:main raylib-examples.image-channel}
             :image-kernel    {:main raylib-examples.image-kernel}
             :cellular-automata {:main raylib-examples.cellular-automata}
             :magnifying-glass {:main raylib-examples.magnifying-glass}
             :to-image        {:main raylib-examples.to-image}
             :polygon-drawing {:main raylib-examples.polygon-drawing}
             :raw-data        {:main raylib-examples.raw-data}
             :textured-curve  {:main raylib-examples.textured-curve}
             :gif-player      {:main raylib-examples.gif-player}
             :window-flags    {:main raylib-examples.window-flags}
             :render-texture  {:main raylib-examples.render-texture}
             :monitor-detector {:main raylib-examples.monitor-detector}
             :input-actions   {:main raylib-examples.input-actions}
             :highdpi-demo    {:main raylib-examples.highdpi-demo}
             :highdpi-testbed {:main raylib-examples.highdpi-testbed}
             :textured-cube   {:main raylib-examples.textured-cube}
             :directional-billboard {:main raylib-examples.directional-billboard}
             :random-sequence {:main raylib-examples.random-sequence}
             :basic-voxel     {:main raylib-examples.basic-voxel}
             :rotating-cube   {:main raylib-examples.rotating-cube}
             :clipboard-text  {:main raylib-examples.clipboard-text}
             :undo-redo       {:main raylib-examples.undo-redo}
             :directory-files {:main raylib-examples.directory-files}
             :custom-logging  {:main raylib-examples.custom-logging}
             :drop-files      {:main raylib-examples.drop-files}
             :text-file-loading {:main raylib-examples.text-file-loading}
             :rectangle-bounds {:main raylib-examples.rectangle-bounds}
             :compute-hash    {:main raylib-examples.compute-hash}
             :storage-values  {:main raylib-examples.storage-values}
             :keyboard-testbed {:main raylib-examples.keyboard-testbed}
             :input-gestures-testbed {:main raylib-examples.input-gestures-testbed}
             :viewport-scaling {:main raylib-examples.viewport-scaling}
             :codepoints-loading {:main raylib-examples.codepoints-loading}
             :unicode-ranges  {:main raylib-examples.unicode-ranges}
             :inline-styling  {:main raylib-examples.inline-styling}
             :unicode-emojis  {:main raylib-examples.unicode-emojis}
             :text-3d-drawing {:main raylib-examples.text-3d-drawing}
             :strings-management {:main raylib-examples.strings-management}
             :shapes-textures-shader {:main raylib-examples.shapes-textures-shader}
             :texture-outline {:main raylib-examples.texture-outline}
             :camera-3d-free  {:main raylib-examples.camera-3d-free}
             :camera-3d-first-person {:main raylib-examples.camera-3d-first-person}
             :texture-waves   {:main raylib-examples.texture-waves}
             :camera-3d-split-screen {:main raylib-examples.camera-3d-split-screen}
             :camera-3d-fps   {:main raylib-examples.camera-3d-fps}
             :vr-simulator    {:main raylib-examples.vr-simulator}
             :automation-events {:main raylib-examples.automation-events}
             :input-gamepad   {:main raylib-examples.input-gamepad}
             :julia-set       {:main raylib-examples.julia-set}
             :framebuffer-rendering {:main raylib-examples.framebuffer-rendering}
             :eratosthenes-sieve {:main raylib-examples.eratosthenes-sieve}
             :mandelbrot-set  {:main raylib-examples.mandelbrot-set}
             :rounded-rectangle-shader {:main raylib-examples.rounded-rectangle-shader}
             :raymarching     {:main raylib-examples.raymarching}
             :color-correction {:main raylib-examples.color-correction}
             :custom-uniform  {:main raylib-examples.custom-uniform}
             :ascii-rendering {:main raylib-examples.ascii-rendering}
             :postprocessing  {:main raylib-examples.postprocessing}
             :texture-rendering {:main raylib-examples.texture-rendering}
             :multi-sample2d  {:main raylib-examples.multi-sample2d}
             :palette-switch  {:main raylib-examples.palette-switch}
             :hot-reloading   {:main raylib-examples.hot-reloading}
             :spotlight-rendering {:main raylib-examples.spotlight-rendering}
             :font-sdf        {:main raylib-examples.font-sdf}
             :depth-writing   {:main raylib-examples.depth-writing}
             :depth-rendering {:main raylib-examples.depth-rendering}
             :hybrid-rendering {:main raylib-examples.hybrid-rendering}
             :texture-tiling  {:main raylib-examples.texture-tiling}
             :model-loading   {:main raylib-examples.model-loading}
             :model-shader    {:main raylib-examples.model-shader}
             :heightmap-rendering {:main raylib-examples.heightmap-rendering}
             :cubicmap-rendering {:main raylib-examples.cubicmap-rendering}
             :mesh-generation {:main raylib-examples.mesh-generation}
             :first-person-maze {:main raylib-examples.first-person-maze}
             :basic-lighting  {:main raylib-examples.basic-lighting}
             :fog-rendering   {:main raylib-examples.fog-rendering}
             :cel-shading     {:main raylib-examples.cel-shading}
             :normalmap-rendering {:main raylib-examples.normalmap-rendering}
             :simple-mask     {:main raylib-examples.simple-mask}
             :vertex-displacement {:main raylib-examples.vertex-displacement}
             :rlgl-compute    {:main raylib-examples.rlgl-compute}
             :mesh-instancing {:main raylib-examples.mesh-instancing}
             :lightmap-rendering {:main raylib-examples.lightmap-rendering}
             :shadowmap-rendering {:main raylib-examples.shadowmap-rendering}
             :basic-pbr       {:main raylib-examples.basic-pbr}
             :deferred-rendering {:main raylib-examples.deferred-rendering}
             :game-of-life    {:main raylib-examples.game-of-life}
             :loading-gltf    {:main raylib-examples.loading-gltf}
             :yaw-pitch-roll  {:main raylib-examples.yaw-pitch-roll}
             :mesh-picking    {:main raylib-examples.mesh-picking}
             :loading-iqm     {:main raylib-examples.loading-iqm}
             :loading-m3d     {:main raylib-examples.loading-m3d}
             :loading-vox     {:main raylib-examples.loading-vox}
             :animation-timing {:main raylib-examples.animation-timing}
             :bone-socket     {:main raylib-examples.bone-socket}
             :point-rendering {:main raylib-examples.point-rendering}
             :skybox-rendering {:main raylib-examples.skybox-rendering}
             :animation-blending {:main raylib-examples.animation-blending}
             :animation-blend-custom {:main raylib-examples.animation-blend-custom}
             :decals          {:main raylib-examples.decals}
             :raw-stream      {:main raylib-examples.raw-stream}
             :mixed-processor {:main raylib-examples.mixed-processor}
             :stream-effects  {:main raylib-examples.stream-effects}
             :stream-callback {:main raylib-examples.stream-callback}
             :amp-envelope    {:main raylib-examples.amp-envelope}
             :spectrum-visualizer {:main raylib-examples.spectrum-visualizer}
             :screen-buffer   {:main raylib-examples.screen-buffer}})
